import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { ProgressRing } from './ProgressRing';
export function MemberTile({ member }) {
    const done = member.instances.filter((i) => ['done', 'done_unapproved', 'skipped'].includes(i.state)).length;
    const total = member.instances.length;
    const pending = total - done;
    return (_jsxs(Link, { to: `/member/${member.slug}`, className: "themed tile relative block rounded-xl4 p-6 sm:p-10 min-h-[22rem] shadow-tile transition-transform active:scale-[0.98] focus-visible:outline-offset-4 focus-visible:outline-white", style: { ['--accent']: member.color }, children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("div", { className: "min-w-0", children: [_jsx("div", { className: "text-fluid-xl font-black truncate", children: member.name }), _jsx("div", { className: "mt-2 text-fluid-sm opacity-90 font-semibold", children: total === 0
                                    ? 'No chores today 🎉'
                                    : `${done} of ${total} done · ${pending} to go` })] }), member.avatar ? (member.avatar.startsWith('/') ? (_jsx("img", { src: member.avatar, alt: "", className: "size-24 sm:size-32 rounded-full object-cover ring-4 ring-white/40" })) : (_jsx("span", { className: "text-[clamp(3rem,8vw,6rem)]", "aria-hidden": true, children: member.avatar }))) : (_jsx("span", { className: "text-[clamp(3rem,8vw,6rem)]", "aria-hidden": true, children: "\uD83E\uDDD2" }))] }), _jsxs("div", { className: "mt-8 flex items-end justify-between gap-6", children: [_jsxs("div", { className: "text-white", children: [_jsxs("div", { className: "flex items-baseline gap-2 text-fluid-sm font-semibold opacity-90", children: [_jsx("span", { "aria-hidden": true, children: "\uD83D\uDD25" }), _jsxs("span", { children: [member.stats.streak, " day", member.stats.streak === 1 ? '' : 's', " streak"] })] }), _jsxs("div", { className: "mt-1 text-fluid-sm font-semibold opacity-90", children: ["\u2B50 ", member.stats.points_this_week, " this week \u00B7 ", member.stats.points_total, " total"] })] }), _jsx(ProgressRing, { percent: member.today_progress_pct, size: 112, color: "white", trackColor: "rgba(255,255,255,0.25)" })] })] }));
}
